export const CHANGE_EMPRESA_PESQUISA_VISIBILITY = 'CHANGE_EMPRESA_PESQUISA_VISIBILITY';
export const CHANGE_USUARIO_OPCOES_VISIBILITY = 'CHANGE_USUARIO_OPCOES_VISIBILITY';

export const CHANGE_MODAL_VISIBILITY = 'CHANGE_MODAL_VISIBILITY';
export const OPEN_MODAL = 'OPEN_MODAL';
export const OPEN_MODAL_AND_UPDATE_DROPDOWN = 'OPEN_MODAL_AND_UPDATE_DROPDOWN';
export const OPEN_MODAL_AND_UPDATE_FORM_ARRAY = 'OPEN_MODAL_AND_UPDATE_FORM_ARRAY';
export const OPEN_MODAL_AND_RELOAD_OTHER_ENTITY = 'OPEN_MODAL_AND_RELOAD_OTHER_ENTITY';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const LOADING = 'LOADING';
export const LOADING_SUCESS = 'LOADING_SUCESS';
export const LOADING_FALIED = 'LOADING_FALIED';

export const SEARCH_SUCESS = 'SEARCH_SUCESS';
export const SEARCH_FALIED = 'SEARCH_FALIED';

export const SAVE_SUCESS = 'SAVE_SUCESS';
export const SAVE_FALIED = 'SAVE_FALIED';

export const UPDATE_SUCESS = 'UPDATE_SUCESS';
export const UPDATE_LIST_SUCESS = 'UPDATE_LIST_SUCESS';
export const UPDATE_FALIED = 'UPDATE_FALIED';

export const DELETE_SUCESS = 'DELETE_SUCESS';
export const DELETE_FALIED = 'DELETE_FALIED';

export const OK_NO_UPDATE = 'OK_NO_UPDATE';

export const CLEAR_LIST = 'CLEAR_LIST';

export const LOAD_USER_LOGGED_DATA = 'LOAD_USER_LOGGED_DATA';

export const RELOAD_IMAGE_CACHE = 'RELOAD_IMAGE_CACHE';
