export const TAB_COLABORADOR = 'TAB_COLABORADOR'
export const TAB_COLABORADOR_CADASTRO = 'TAB_COLABORADOR_CADASTRO'
export const COLABORADOR_BUTTON_ADICIONAR = 'COLABORADOR_BUTTON_ADICIONAR'

export const BUSCA_CARGOS = 'BUSCA_CARGOS'
export const BUSCA_DEPARTAMENTOS = 'BUSCA_DEPARTAMENTOS'

export const CHANGE_ROUTER = 'CHANGE_ROUTER'
