export const TAB_COLABORADOR = 'TAB_COLABORADOR'
export const TAB_COLABORADOR_CADASTRO = 'TAB_COLABORADOR_CADASTRO'
export const COLABORADOR_BUTTON_ADICIONAR = 'COLABORADOR_BUTTON_ADICIONAR'

export const BUSCA_CARGOS = 'BUSCA_CARGOS'
export const BUSCA_DEPARTAMENTOS = 'BUSCA_DEPARTAMENTOS'

export const CHANGE_ROUTER = 'CHANGE_ROUTER'

export const TAB_FOLHA_PAGAMENTO = 'TAB_FOLHA_PAGAMENTO'

export const CHANGE_VISIBILITY_MODAL_HOLERITE = 'CHANGE_VISIBILITY_MODAL_HOLERITE'

export const CHANGE_EMPRESA_PESQUISA_VISIBILITY = 'CHANGE_EMPRESA_PESQUISA_VISIBILITY'
export const CHANGE_USUARIO_OPCOES_VISIBILITY = 'CHANGE_USUARIO_OPCOES_VISIBILITY'

export const TAB_CONFIGURACAO = 'TAB_CONFIGURACAO'

export const CHANGE_MODAL_VISIBILITY = 'CHANGE_MODAL_VISIBILITY'

export const LOADING = 'LOADING'
export const LOADING_SUCESS = 'LOADING_SUCESS'
export const LOADING_FALIED = 'LOADING_FALIED'

export const SEARCH_SUCESS = 'SEARCH_SUCESS'
export const SEARCH_FALIED = 'SEARCH_FALIED'

export const SAVE_SUCESS = 'SAVE_SUCESS'
export const SAVE_FALIED = 'SAVE_FALIED'

export const UPDATE_SUCESS = 'UPDATE_SUCESS'
export const UPDATE_FALIED = 'UPDATE_FALIED'

export const DELETE_SUCESS = 'DELETE_SUCESS'
export const DELETE_FALIED = 'DELETE_FALIED'
